### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by RaGgOtArc** [darkdragn/party#15]
When I use the `party search anaimiya coomer -i` to download this blogger's posts, after a while it reports an SSL error. When I use the `party update anaimiya` command to update again, it will report an error directly. 

The error message is as follows:
`(PartyDownloader) F:\coomer>party update anaimiya
2023-08-27 18:03:55.010 | DEBUG    | party.cli:pull_user:80 - Excluded Extensions: []
urllib3.exceptions.SSLError: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1002)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "C:\Users\user\anaconda3\envs\PartyDownloader\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^

  File "C:\Users\user\anaconda3\envs\PartyDownloader\Lib\site-packages\urllib3\connectionpool.py", line 844, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^

  File "C:\Users\user\anaconda3\envs\PartyDownloader\Lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='coomer.party', port=443): Max retries exceeded with url: /api/onlyfans/user/anaimiya?o=250&limit=50 (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1002)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "<frozen runpy>", line 198, in _run_module_as_main

  File "<frozen runpy>", line 88, in _run_code

  File "C:\Users\user\anaconda3\envs\PartyDownloader\Scripts\party.exe\__main__.py", line 7, in <module>
    sys.exit(APP())
             ^^^^^

  File "C:\Users\user\anaconda3\envs\PartyDownloader\Lib\site-packages\party\cli.py", line 363, in update
    pull_user(

  File "C:\Users\user\anaconda3\envs\PartyDownloader\Lib\site-packages\party\cli.py", line 106, in pull_user
    embedded = [embed for p in user.posts if (embed := p.embed)]
                               ^^^^^^^^^^

  File "C:\Users\user\anaconda3\envs\PartyDownloader\Lib\functools.py", line 1001, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^

  File "C:\Users\user\anaconda3\envs\PartyDownloader\Lib\site-packages\party\user.py", line 133, in posts
    return list(self.generate_posts())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\user\anaconda3\envs\PartyDownloader\Lib\site-packages\party\user.py", line 82, in generate_posts
    resp = requests.get(self.url, params=dict(o=offset, limit=50))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\user\anaconda3\envs\PartyDownloader\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\user\anaconda3\envs\PartyDownloader\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\user\anaconda3\envs\PartyDownloader\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\user\anaconda3\envs\PartyDownloader\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\user\anaconda3\envs\PartyDownloader\Lib\site-packages\requests\adapters.py", line 517, in send
    raise SSLError(e, request=request)

requests.exceptions.SSLError: HTTPSConnectionPool(host='coomer.party', port=443): Max retries exceeded with url: /api/onlyfans/user/anaimiya?o=250&limit=50 (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1002)')))

(PartyDownloader) F:\coomer>party update anaimiya
2023-08-27 18:09:30.959 | DEBUG    | party.cli:pull_user:80 - Excluded Extensions: []
urllib3.exceptions.SSLError: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1002)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "C:\Users\user\anaconda3\envs\PartyDownloader\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^

  File "C:\Users\user\anaconda3\envs\PartyDownloader\Lib\site-packages\urllib3\connectionpool.py", line 844, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^

  File "C:\Users\user\anaconda3\envs\PartyDownloader\Lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='coomer.party', port=443): Max retries exceeded with url: /api/onlyfans/user/anaimiya?o=0&limit=50 (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1002)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "<frozen runpy>", line 198, in _run_module_as_main

  File "<frozen runpy>", line 88, in _run_code

  File "C:\Users\user\anaconda3\envs\PartyDownloader\Scripts\party.exe\__main__.py", line 7, in <module>
    sys.exit(APP())
             ^^^^^

  File "C:\Users\user\anaconda3\envs\PartyDownloader\Lib\site-packages\party\cli.py", line 363, in update
    pull_user(

  File "C:\Users\user\anaconda3\envs\PartyDownloader\Lib\site-packages\party\cli.py", line 105, in pull_user
    posts = list(user.limit_posts(limit))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\user\anaconda3\envs\PartyDownloader\Lib\site-packages\party\user.py", line 82, in generate_posts
    resp = requests.get(self.url, params=dict(o=offset, limit=50))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\user\anaconda3\envs\PartyDownloader\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\user\anaconda3\envs\PartyDownloader\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\user\anaconda3\envs\PartyDownloader\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\user\anaconda3\envs\PartyDownloader\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\user\anaconda3\envs\PartyDownloader\Lib\site-packages\requests\adapters.py", line 517, in send
    raise SSLError(e, request=request)

requests.exceptions.SSLError: HTTPSConnectionPool(host='coomer.party', port=443): Max retries exceeded with url: /api/onlyfans/user/anaimiya?o=0&limit=50 (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1002)')))`

**Comment by darkdragn** [comment]
Hey, I just woke up. I have some family things to do, but here in a couple of hours I'll take a look and see if I can't figure out what's happening.

I should have either a patch together by this evening or get you an update.
