### ISSUE TITLE
ModuleNotFoundError: No module named 'pkg_resources'

### ISSUE THREAD

**Issue by dabigwillyhaver** [darkdragn/party#38]
Not exactly sure what I'm doing wrong, I've gotten this to work on my previous computer but now I seem unable to get it to function, here's the full error:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\jack\AppData\Local\Programs\Python\Python312\Scripts\party.exe\__main__.py", line 4, in <module>
  File "C:\Users\jack\AppData\Local\Programs\Python\Python312\Lib\site-packages\party\cli.py", line 18, in <module>
    from marshmallow_jsonschema import JSONSchema
  File "C:\Users\jack\AppData\Local\Programs\Python\Python312\Lib\site-packages\marshmallow_jsonschema\__init__.py", line 1, in <module>
    from pkg_resources import get_distribution
ModuleNotFoundError: No module named 'pkg_resources'

Help would be much appreciated.

**Comment by darkdragn** [comment]
There are some dependencies for this that don't play nice with python 3.12.

That's what's being off here. Try downgrading to anything between 3.9-3.11 and you shouldn't have any issues.

I did notice some schemas changes last night that was working gumroad pulls. I don't know if they're impacting other hosting services, but I'll have the fix for those schema changes up later in the evening, if you run into that problem.

**Comment by dabigwillyhaver** [comment]
Downgraded to 11.8, works now. Thanks for the help.
