### ISSUE TITLE
Connection Timeout Error

### ISSUE THREAD

**Issue by paulmuaddibusulatreides** [darkdragn/party#39]
Got this error
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='coomer.su', port=443): Max retries exceeded with url: /api/v1/creators.txt (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000011A7CFDADB0>, 'Connection to coomer.su timed out. (connect timeout=90)'))

**Comment by paulmuaddibusulatreides** [comment]
New error today, geting similar error for other creators.

Downloading from user: tessafowler
  0%|                                                                                                                                                                                    | 0/91 [00:03<?, ?it/s]
Traceback (most recent call last):

  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiohttp\connector.py", line 992, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1120, in create_connection
    raise exceptions[0]

  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1102, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1005, in _connect_sock
    await self.sock_connect(sock, address)

  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\asyncio\proactor_events.py", line 727, in sock_connect
    return await self._proactor.connect(sock, address)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 798, in _poll
    value = callback(transferred, key, ov)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 594, in finish_connect
    ov.getresult()

ConnectionRefusedError: [WinError 1225] The remote computer refused the network connection


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "<frozen runpy>", line 198, in _run_module_as_main

  File "<frozen runpy>", line 88, in _run_code

  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Scripts\party.exe\__main__.py", line 7, in <module>
    sys.exit(APP())
             ^^^^^

  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\party\cli.py", line 293, in coomer
    pull_user(**ctx.params)

  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\party\cli.py", line 211, in pull_user
    output = asyncio.run(
             ^^^^^^^^^^^^

  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^

  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^

  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\party\cli.py", line 269, in download_async
    temp = await asyncio.gather(*downloads)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\party\cli.py", line 252, in download
    status = await file.download(
             ^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\party\posts.py", line 140, in download
    async with session.head(url, allow_redirects=True) as head:

  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiohttp\client.py", line 1187, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^

  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiohttp\client.py", line 574, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiohttp\connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiohttp\connector.py", line 911, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiohttp\connector.py", line 1235, in _create_direct_connection
    raise last_exc

  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiohttp\connector.py", line 1204, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiohttp\connector.py", line 1000, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc

aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host c4.coomer.su:443 ssl:default [The remote computer refused the network connection]

**Comment by darkdragn** [comment]
I just added some error handling and a new retry policy to resolve this. 

It's on the latest release. Please give it a try and let me know if it fixes these for you!
