### ISSUE TITLE
JSON decode error

### ISSUE THREAD

**Issue by lolbroek-droid** [darkdragn/party#42]
i don't know what happened here but i got this error almost instantly after running the command

```
Traceback (most recent call last):

  File "/home/user/.local/bin/party", line 8, in <module>
    sys.exit(APP())

  File "/home/user/.local/lib/python3.10/site-packages/party/cli.py", line 293, in coomer
    pull_user(**ctx.params)

  File "/home/user/.local/lib/python3.10/site-packages/party/cli.py", line 130, in pull_user
    user = User.get_user(site, service, user_id)

  File "/home/user/.local/lib/python3.10/site-packages/party/user.py", line 77, in get_user
    users = cls.generate_users(base_url)

  File "/home/user/.local/lib/python3.10/site-packages/party/user.py", line 48, in generate_users
    return UserSchema(context={"site": base_url}, unknown=EXCLUDE).loads(

  File "/home/user/.local/lib/python3.10/site-packages/marshmallow/schema.py", line 755, in loads
    data = self.opts.render_module.loads(json_data, **kwargs)

  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)

  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

  File "/usr/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)

json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 1404027 (char 1404026)
```

**Comment by lolbroek-droid** [comment]
after a reboot it changed
```
Traceback (most recent call last):

  File "/home/user/.local/bin/party", line 8, in <module>
    sys.exit(APP())

  File "/home/user/.local/lib/python3.10/site-packages/party/cli.py", line 293, in coomer
    pull_user(**ctx.params)

  File "/home/user/.local/lib/python3.10/site-packages/party/cli.py", line 130, in pull_user
    user = User.get_user(site, service, user_id)

  File "/home/user/.local/lib/python3.10/site-packages/party/user.py", line 77, in get_user
    users = cls.generate_users(base_url)

  File "/home/user/.local/lib/python3.10/site-packages/party/user.py", line 48, in generate_users
    return UserSchema(context={"site": base_url}, unknown=EXCLUDE).loads(

  File "/home/user/.local/lib/python3.10/site-packages/marshmallow/schema.py", line 755, in loads
    data = self.opts.render_module.loads(json_data, **kwargs)

  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)

  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

  File "/usr/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)

json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 996765 (char 996764)

```

**Comment by lolbroek-droid** [comment]
this is running on ubuntu btw

**Comment by lolbroek-droid** [comment]
even on a fresh install it still persists

**Comment by lolbroek-droid** [comment]
suddenly it works again

**Comment by lolbroek-droid** [comment]
and broke again

**Comment by lolbroek-droid** [comment]
ok so i deleted the .post .etags and .info files and it worked again
